import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Play, Cpu, Mic, Globe, Zap, Shield, Check, Square, MessageSquare, Bot } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { dashboardApi, type DashboardOverview, type BlogPost } from '../services/dashboardApi';
import { PricingPlans } from '../components/PricingPlans';
import { API_ORIGIN_BASE } from '../services/baseUrl';
import { asset } from '../data/assets';

gsap.registerPlugin(ScrollTrigger);

const DASHBOARD_BASE = API_ORIGIN_BASE;

const ROADMAP_QUARTERS = [
  {
    phase: 'Q1 – Foundation',
    completed: true,
    items: [
      'Subnet launch on Bittensor',
      'Official website and monitoring dashboard',
      'Baseline evaluation pipeline for PromptTTS focused on voice quality validation, voice trait accuracy, content correctness, and environmental consistency',
    ],
  },
  {
    phase: 'Q2 – Scaling and Robustness',
    completed: false,
    items: [
      'Expanded voice-trait and environmental taxonomy',
      'Baseline evaluation pipeline for STT, Voice Cloning on the subnet',
      'Start collecting datasets for model training from validator results submitted by miners and generated by validator task generation/evaluation pipeline',
      'Adversarial prompt testing to reduce overfitting and prompt gaming',
      'Subnet product launch (PromptTTS, STT, Voice Cloning) and API for developers',
    ],
  },
  {
    phase: 'Q3 – Ecosystem Expansion',
    completed: false,
    items: [
      'Launch Voice STS, TTM pipeline on the subnet and begin competition',
      'Platform expansion with Voice AI Agents that integrate with developed multimodal models. Make them integrable with voice applications and other platform voice agents',
      'Platform expansion to support various APIs that integrate with other APIs, services, and external platforms',
      'Cross-subnet integrations within the Bittensor ecosystem',
      'Advanced controllability and expressiveness benchmarks across all voice domains',
    ],
  },
];

function blogImageUrl(url: string): string {
  if (!url) return '';
  if (url.startsWith('http')) return url;
  return `${DASHBOARD_BASE}${url.startsWith('/') ? '' : '/'}${url}`;
}

export function Overview() {
  const [overview, setOverview] = useState<DashboardOverview | null>(null);
  const [latestPosts, setLatestPosts] = useState<BlogPost[]>([]);
  const [postsLoading, setPostsLoading] = useState(true);
  const [samplePlaying, setSamplePlaying] = useState(false);
  const sampleAudioRef = useRef<HTMLAudioElement>(null);
  const heroRef = useRef<HTMLDivElement>(null);
  const featuresRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLDivElement>(null);
  const statsRef = useRef<HTMLDivElement>(null);
  const howItWorksRef = useRef<HTMLDivElement>(null);
  const useCasesRef = useRef<HTMLDivElement>(null);
  const newsRef = useRef<HTMLDivElement>(null);
  const videoElementRef = useRef<HTMLVideoElement>(null);
  const usecaseVideoRefs = useRef<(HTMLVideoElement | null)[]>([]);
  const [roadmapActive, setRoadmapActive] = useState(0);

  useEffect(() => {
    dashboardApi.getOverview().then(setOverview).catch(() => setOverview(null));
  }, []);

  useEffect(() => {
    setPostsLoading(true);
    dashboardApi
      .getBlogPosts(3, 0)
      .then((res) => setLatestPosts((res.posts || []).slice(0, 3)))
      .catch(() => setLatestPosts([]))
      .finally(() => setPostsLoading(false));
  }, []);

  const toggleSamplePlayback = () => {
    const el = sampleAudioRef.current;
    if (!el) return;
    if (samplePlaying) {
      el.pause();
      el.currentTime = 0;
      setSamplePlaying(false);
    } else {
      el.loop = true;
      el.play().catch(() => setSamplePlaying(false));
      setSamplePlaying(true);
    }
  };

  useEffect(() => {
    const el = sampleAudioRef.current;
    if (!el) return;
    const onEnded = () => setSamplePlaying(false);
    const onPause = () => setSamplePlaying(false);
    el.addEventListener('ended', onEnded);
    el.addEventListener('pause', onPause);
    return () => {
      el.removeEventListener('ended', onEnded);
      el.removeEventListener('pause', onPause);
    };
  }, []);

  useEffect(() => {
    const ctx = gsap.context(() => {
      // Hero animations
      gsap.fromTo(
        '.hero-eyebrow',
        { opacity: 0, y: 20 },
        { opacity: 1, y: 0, duration: 0.6, delay: 0.3 }
      );
      gsap.fromTo(
        '.hero-title',
        { opacity: 0, y: 40 },
        { opacity: 1, y: 0, duration: 0.8, delay: 0.5 }
      );
      gsap.fromTo(
        '.hero-subtitle',
        { opacity: 0, y: 20 },
        { opacity: 1, y: 0, duration: 0.6, delay: 0.7 }
      );
      gsap.fromTo(
        '.hero-cta',
        { opacity: 0, y: 20 },
        { opacity: 1, y: 0, duration: 0.6, delay: 0.9 }
      );

      // Features section: cards and content reveal left-to-right, then content “fills in” per card
      gsap.fromTo(
        '.feature-card',
        { opacity: 0, y: 32 },
        {
          opacity: 1,
          y: 0,
          duration: 0.55,
          stagger: 0.1,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: featuresRef.current,
            start: 'top 82%',
          },
        }
      );
      gsap.fromTo(
        '.feature-icon',
        { opacity: 0, scale: 0.85 },
        {
          opacity: 1,
          scale: 1,
          duration: 0.4,
          stagger: 0.1,
          delay: 0.08,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: featuresRef.current,
            start: 'top 82%',
          },
        }
      );
      gsap.fromTo(
        '.feature-card-title',
        { opacity: 0, y: 10 },
        {
          opacity: 1,
          y: 0,
          duration: 0.4,
          stagger: 0.1,
          delay: 0.2,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: featuresRef.current,
            start: 'top 82%',
          },
        }
      );
      gsap.fromTo(
        '.feature-card-desc',
        { opacity: 0, y: 8 },
        {
          opacity: 1,
          y: 0,
          duration: 0.45,
          stagger: 0.1,
          delay: 0.35,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: featuresRef.current,
            start: 'top 82%',
          },
        }
      );

      // Stats section - more dramatic
      gsap.fromTo(
        '.stat-item',
        { opacity: 0, x: -50, scale: 0.8 },
        {
          opacity: 1,
          x: 0,
          scale: 1,
          duration: 0.7,
          stagger: 0.12,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: statsRef.current,
            start: 'top 85%',
          },
        }
      );

      // Stat numbers animation (pulse effect)
      gsap.utils.toArray('.stat-number').forEach((stat: any) => {
        gsap.fromTo(
          stat,
          { scale: 0.8, opacity: 0.5 },
          {
            scale: 1,
            opacity: 1,
            duration: 0.8,
            ease: 'back.out(1.7)',
            scrollTrigger: {
              trigger: stat,
              start: 'top 85%',
            },
          }
        );
      });

      // How it works - more dramatic
      gsap.fromTo(
        '.step-card',
        { opacity: 0, y: 80, scale: 0.85, rotationY: 15 },
        {
          opacity: 1,
          y: 0,
          scale: 1,
          rotationY: 0,
          duration: 0.9,
          stagger: 0.2,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: howItWorksRef.current,
            start: 'top 85%',
          },
        }
      );

      // Step images parallax effect
      gsap.utils.toArray('.step-image').forEach((img: any) => {
        gsap.to(img, {
          y: -30,
          scrollTrigger: {
            trigger: img,
            start: 'top bottom',
            end: 'bottom top',
            scrub: 1,
          },
        });
      });

      // Use cases - more dramatic
      gsap.fromTo(
        '.usecase-card',
        { opacity: 0, scale: 0.7, rotation: -5 },
        {
          opacity: 1,
          scale: 1,
          rotation: 0,
          duration: 0.7,
          stagger: 0.1,
          ease: 'back.out(1.4)',
          scrollTrigger: {
            trigger: useCasesRef.current,
            start: 'top 85%',
          },
        }
      );

      // News section - more dramatic
      gsap.fromTo(
        '.news-card',
        { opacity: 0, y: 50, scale: 0.9 },
        {
          opacity: 1,
          y: 0,
          scale: 1,
          duration: 0.8,
          stagger: 0.12,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: newsRef.current,
            start: 'top 85%',
          },
        }
      );

      // Demo video section animation
      if (videoRef.current) {
        gsap.fromTo(
          '.demo-video-container',
          { opacity: 0, scale: 0.95, y: 60 },
          {
            opacity: 1,
            scale: 1,
            y: 0,
            duration: 1,
            ease: 'power3.out',
            scrollTrigger: {
              trigger: videoRef.current,
              start: 'top 85%',
            },
          }
        );

        gsap.fromTo(
          '.demo-video-content',
          { opacity: 0, x: -40 },
          {
            opacity: 1,
            x: 0,
            duration: 0.8,
            delay: 0.3,
            ease: 'power2.out',
            scrollTrigger: {
              trigger: videoRef.current,
              start: 'top 85%',
            },
          }
        );
      }

      // Section headers animation
      gsap.utils.toArray('.section-header').forEach((header: any) => {
        gsap.fromTo(
          header,
          { opacity: 0, y: 30 },
          {
            opacity: 1,
            y: 0,
            duration: 0.8,
            scrollTrigger: {
              trigger: header,
              start: 'top 90%',
            },
          }
        );
      });
    });

    return () => ctx.revert();
  }, []);

  return (
    <div className="bg-[#07080A]">
      {/* Hero Section */}
      <section
        ref={heroRef}
        className="relative min-h-screen flex items-center justify-center overflow-hidden"
      >
        {/* Background Image */}
        <div className="absolute inset-0">
          <img
            src="/hero_portrait.jpg"
            alt="Hero background"
            className="w-full h-full object-cover opacity-60"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-[#07080A] via-[#07080A]/80 to-transparent" />
          <div className="absolute inset-0 bg-gradient-to-t from-[#07080A] via-transparent to-[#07080A]/50" />
        </div>

        {/* Content */}
        <div className="relative z-10 max-w-7xl mx-auto px-6 lg:px-8 pt-32 pb-20">
          <div className="max-w-3xl">
            <span className="hero-eyebrow inline-block px-4 py-1.5 rounded-full bg-[#DFFF00]/10 border border-[#DFFF00]/20 text-[#DFFF00] text-xs font-mono uppercase tracking-wider mb-6">
              BITTENSOR SUBNET 78
            </span>
            <h1 className="hero-title text-5xl md:text-7xl font-semibold tracking-tight leading-[1.1] mb-6">
              The voice layer for{' '}
              <span className="gradient-text">decentralized intelligence.</span>
            </h1>
            <p className="hero-subtitle text-lg md:text-xl text-[#A7B0B7] leading-relaxed mb-8 max-w-2xl">
              Voice intelligence network on Bittensor
            </p>
            <div className="hero-cta flex flex-wrap gap-4">
              <Link to="/studio/tts" className="btn-primary">
                Open Studio
                <ArrowRight size={18} className="ml-2" />
              </Link>
              <Link to="/dashboard" className="btn-outline">
                Network Dashboard
              </Link>
              <Link to="/whitepaper" className="btn-outline">
                Whitepaper
              </Link>
              <Link to="/docs" className="btn-outline">
                Read the Docs
              </Link>
            </div>
          </div>
        </div>

        {/* Bottom Status Bar */}
        <div className="absolute bottom-8 left-6 lg:left-8 flex items-center gap-2 px-4 py-2 rounded-full border border-white/10 bg-white/5">
          <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
          <span className="text-xs font-mono text-[#A7B0B7]">Mainnet</span>
          <span className="text-xs text-[#666]">|</span>
          <span className="text-xs text-[#A7B0B7]">Network Status: Healthy</span>
        </div>

      </section>

      {/* What is Vocence Section */}
      <section ref={featuresRef} className="py-24 px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16 section-header">
            <span className="label-mono mb-4 block">What is Vocence?</span>
            <h2 className="text-3xl md:text-4xl font-semibold mb-4">
              Voice Intelligence Layer
            </h2>
            <p className="text-[#A7B0B7] max-w-2xl mx-auto">
              Prompts become natural speech and voice responses. Multiple domains, one network, open benchmarks.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                icon: Mic,
                title: 'Prompt-to-Speech',
                description: 'Text and style prompt become natural speech. Control tone emotion and accent.',
                image: '/prompt_to_speech_image.png',
              },
              {
                icon: MessageSquare,
                title: 'STT, Cloning & Music',
                description: 'Transcribe speech, clone voices, design custom voices, and generate music. Full voice and audio stack.',
                image: '/stt_sts_cloning_image.png',
              },
              {
                icon: Bot,
                title: 'Voice Agents',
                description: 'TTS STT and reasoning in one place. Build voice-driven apps.',
                image: '/voice_agents_image.png',
              },
              {
                icon: Shield,
                title: 'Decentralized and Open',
                description: 'Miners compete validators score publicly. No black boxes.',
                image: '/decentralized_and_open_image.png',
              },
            ].map((feature, index) => (
              <div
                key={index}
                className="feature-card group relative overflow-hidden rounded-2xl border border-white/10 p-8 transition-all duration-300 hover:border-[#DFFF00]/40 hover:shadow-[0_0_24px_-4px_rgba(223,255,0,0.15)]"
              >
                <div
                  className="absolute inset-0 transition-transform duration-500 ease-out group-hover:scale-125"
                  style={{ backgroundImage: `url(${feature.image})`, backgroundSize: 'cover', backgroundPosition: 'center' }}
                  aria-hidden
                />
                <div className="absolute inset-0 bg-[#07080A]/50 transition-opacity duration-300 group-hover:bg-[#07080A]/35" aria-hidden />
                <div className="absolute left-0 top-0 bottom-0 w-0.5 bg-[#DFFF00]/0 transition-all duration-300 group-hover:bg-[#DFFF00]/50" aria-hidden />
                <div className="feature-icon relative w-12 h-12 rounded-xl bg-[#DFFF00]/10 flex items-center justify-center mb-6 transition-colors duration-300 group-hover:bg-[#DFFF00]/20">
                  <feature.icon size={24} className="text-[#DFFF00]" />
                </div>
                <h3 className="feature-card-title relative text-xl font-semibold mb-3 text-white">{feature.title}</h3>
                <p className="feature-card-desc relative text-[#A7B0B7] text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Demo Video Section */}
      <section ref={videoRef} className="py-24 px-6 lg:px-8 border-y border-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Content */}
            <div className="demo-video-content">
              <span className="label-mono mb-4 block">See It In Action</span>
              <h2 className="text-3xl md:text-4xl font-semibold mb-4">
                Experience Vocence Studio
              </h2>
              <p className="text-[#A7B0B7] mb-6 leading-relaxed">
                See how easy it is to create natural, impressive speech with just a prompt. Describe voice, tone, and style—then get the exact speech you want.
              </p>
              <ul className="space-y-3 mb-8">
                {[
                  'Prompt-driven voice control: tone, style, accent, and emotion',
                  'Content-accurate, prompt-faithful speech generation',
                  'Professional-grade audio quality and naturalness',
                ].map((item, index) => (
                  <li key={index} className="flex items-center gap-3">
                    <span className="text-[#DFFF00]">
                      <Check size={18} />
                    </span>
                    <span className="text-[#A7B0B7]">{item}</span>
                  </li>
                ))}
              </ul>
              <Link to="/studio/tts" className="btn-primary inline-flex items-center">
                Try It Now
                <ArrowRight size={18} className="ml-2" />
              </Link>
            </div>

            {/* Video */}
            <div className="demo-video-container">
              <div 
                className="relative rounded-2xl overflow-hidden border border-white/10 bg-[#0D1117] shadow-2xl group cursor-pointer"
                onClick={() => {
                  if (videoElementRef.current) {
                    if (videoElementRef.current.paused) {
                      videoElementRef.current.play();
                    } else {
                      videoElementRef.current.pause();
                    }
                  }
                }}
              >
                <div className="aspect-video">
                  <video
                    ref={videoElementRef}
                    autoPlay
                    loop
                    muted
                    playsInline
                    className="w-full h-full object-cover"
                  >
                    <source src={asset('video.demo')} type="video/mp4" />
                    Your browser does not support the video tag.
                  </video>
                </div>
                {/* Video overlay gradient */}
                <div className="absolute inset-0 bg-gradient-to-t from-[#07080A]/30 via-transparent to-transparent pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Live Network Stats Section */}
      <section ref={statsRef} className="py-24 px-6 lg:px-8 border-y border-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <span className="label-mono mb-4 block">Live Network</span>
              <h2 className="text-3xl md:text-4xl font-semibold mb-4">
                Real-time Performance
              </h2>
              <p className="text-[#A7B0B7] mb-8">
                Validators score miners every few seconds. The best models rise to the top.
                View the full network dashboard for miners, validators, win rates, and evaluation activity.
              </p>

              <div className="grid grid-cols-3 gap-6">
                <div className="stat-item">
                  <div className="stat-number text-4xl font-bold text-[#DFFF00] mb-1">
                    {overview?.valid_miners != null ? overview.valid_miners.toLocaleString() : '—'}
                  </div>
                  <div className="text-sm text-[#A7B0B7]">Active miners</div>
                </div>
                <div className="stat-item">
                  <div className="stat-number text-4xl font-bold text-white mb-1">
                    {overview?.total_validators != null ? overview.total_validators.toLocaleString() : '—'}
                  </div>
                  <div className="text-sm text-[#A7B0B7]">Validators</div>
                </div>
                <div className="stat-item">
                  <div className="stat-number text-4xl font-bold text-white mb-1">
                    {overview?.total_evaluations != null ? overview.total_evaluations.toLocaleString() : '—'}
                  </div>
                  <div className="text-sm text-[#A7B0B7]">Evaluations</div>
                </div>
              </div>

              <Link
                to="/dashboard"
                className="stat-item mt-8 inline-flex items-center gap-2 px-6 py-3 rounded-xl border border-[#DFFF00]/30 bg-[#DFFF00]/5 text-[#DFFF00] font-medium hover:bg-[#DFFF00]/10 hover:border-[#DFFF00]/50 transition-colors"
              >
                Open Network Dashboard
                <ArrowRight size={18} />
              </Link>
            </div>

            <div className="space-y-3">
              <p className="text-sm text-[#A7B0B7] mb-4">
                The dashboard shows live data. Miner rankings by win rate, validator activity, and evaluation counts over time.
              </p>
              <Link
                to="/dashboard"
                className="stat-item flex items-center justify-between p-4 rounded-xl border border-l-2 border-l-[#DFFF00] bg-white/5 hover:bg-white/10 transition-colors group"
              >
                <div className="flex items-center gap-4">
                  <span className="text-sm font-medium text-white">Network Dashboard</span>
                  <span className="text-xs text-[#666]">Miners · Validators · Metrics</span>
                </div>
                <ArrowRight size={18} className="text-[#DFFF00] group-hover:translate-x-1 transition-transform" />
              </Link>
              <div className="p-4 rounded-xl border border-white/5 bg-white/[0.02]">
                <p className="text-xs text-[#666]">
                  Data is collected from validators via the Vocence API and aggregated for transparent, real-time visibility.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section ref={howItWorksRef} className="py-24 px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <span className="label-mono mb-4 block">How It Works</span>
            <h2 className="text-3xl md:text-4xl font-semibold mb-4">
              Built on Decentralized Intelligence
            </h2>
            <p className="text-[#A7B0B7] max-w-2xl mx-auto">
              Vocence leverages the Bittensor network to create the most advanced prompt-controlled voice synthesis models.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                step: '01',
                title: 'Generate Task',
                description:
                  'Validators create prompts with target voice traits and reference audio.',
                image: '/step_01.jpg',
              },
              {
                step: '02',
                title: 'Mine & Submit',
                description:
                  'Miners continuously improve their models and submit them to the network',
                image: '/step_02.jpg',
              },
              {
                step: '03',
                title: 'Score & Reward',
                description:
                  'Validators evaluate quality and prompt adherence; rewards flow on-chain.',
                image: '/step_03.jpg',
              },
            ].map((step, index) => (
              <div key={index} className="step-card card-vocence overflow-hidden group">
                <div className="h-48 overflow-hidden">
                  <img
                    src={step.image}
                    alt={step.title}
                    className="step-image w-full h-full object-cover opacity-80 group-hover:opacity-100 group-hover:brightness-110 group-hover:scale-110 transition-all duration-500"
                  />
                </div>
                <div className="p-6">
                  <span className="text-5xl font-bold text-white/10 absolute top-4 right-4">
                    {step.step}
                  </span>
                  <h3 className="text-xl font-semibold mb-2">{step.title}</h3>
                  <p className="text-[#A7B0B7] text-sm">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Prompt-to-Speech Demo Section */}
      <section className="py-24 px-6 lg:px-8 border-y border-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <span className="label-mono mb-4 block">Prompt-to-Speech: PromptTTS Models</span>
              <h2 className="text-3xl md:text-4xl font-semibold mb-4">
                Fine-Grained Emotional Control
              </h2>
              <p className="text-[#A7B0B7] mb-6">
                Describe voice, mood, and pacing. The model follows your intent—not just
                the text.
              </p>

              <ul className="space-y-3 mb-8">
                {[
                  'Gender, age, accent, emotion',
                  'Speaking style and emphasis',
                  'Accent, tone, speed, environment',
                ].map((item, index) => (
                  <li key={index} className="flex items-center gap-3">
                    <span className="text-[#DFFF00]">
                      <Check size={18} />
                    </span>
                    <span className="text-[#A7B0B7]">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="card-vocence p-6">
              <audio ref={sampleAudioRef} src={asset('audio.homepage_demo')} preload="metadata" />
              <div className="flex items-center justify-between mb-4">
                <span className="text-xs font-mono text-[#666]">Example prompt</span>
                <button
                  type="button"
                  onClick={toggleSamplePlayback}
                  className="flex items-center gap-2 text-sm text-[#DFFF00] hover:opacity-90"
                >
                  {samplePlaying ? <Square size={16} /> : <Play size={16} />}
                  {samplePlaying ? 'Stop' : 'Play sample'}
                </button>
              </div>
              <p className="text-sm text-[#A7B0B7] mb-6">
                &quot;swamps, omnipresent streams, and viscous mud from the daily rains. The Amtracs proved amazingly flexible. They moved men, ammunition, rations, water, barbed wire, and even radio jeeps to the front lines where they were most needed. Heading back, they evacuated the wounded to reach the | gender: male | emotion: neutral | pitch: normal | tone: formal | environment: quiet | speed: normal | accent: american&quot;
              </p>
              <div className="flex items-end gap-1 h-16">
                {Array.from({ length: 32 }).map((_, i) => (
                  <div
                    key={i}
                    className="w-1 bg-[#DFFF00] rounded-full waveform-bar"
                    style={{
                      height: `${20 + Math.random() * 80}%`,
                      animationDelay: `${i * 0.05}s`,
                    }}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Use Cases Section */}
      <section ref={useCasesRef} className="py-24 px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <span className="label-mono mb-4 block">Use Cases</span>
            <h2 className="text-3xl md:text-4xl font-semibold mb-4">
              Built for Every Voice Application
            </h2>
            <p className="text-[#A7B0B7] max-w-2xl mx-auto">
              From agents to entertainment—anywhere voice needs to be expressive and
              controllable.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { title: 'AI Agents', image: '/usecase_agents.jpg', video: asset('video.ai_agents'), icon: Cpu },
              { title: 'Accessibility', image: '/usecase_accessibility.jpg', video: asset('video.accessibility'), icon: Mic },
              { title: 'Gaming & Characters', image: '/usecase_gaming.jpg', video: asset('video.gaming_characters'), icon: Zap },
              { title: 'Content & Dubbing', image: '/usecase_dubbing.jpg', video: asset('video.content_dubbing'), icon: Globe },
            ].map((usecase, index) => (
              <div
                key={index}
                className="usecase-card group relative overflow-hidden rounded-2xl aspect-square cursor-pointer"
                onMouseEnter={() => {
                  const v = usecaseVideoRefs.current[index];
                  if (v) {
                    v.muted = false;
                    v.removeAttribute('muted');
                    // Let hover/visibility apply then play with sound (browsers may allow unmuted after hover)
                    const playWithSound = () => {
                      v.play().catch(() => {
                        v.muted = true;
                        v.play().catch(() => {});
                      });
                    };
                    requestAnimationFrame(() => requestAnimationFrame(playWithSound));
                  }
                }}
                onMouseLeave={() => {
                  const v = usecaseVideoRefs.current[index];
                  if (v) {
                    v.pause();
                    v.currentTime = 0;
                    v.muted = true;
                  }
                }}
              >
                {/* Image: visible by default, hidden on group-hover so video shows immediately */}
                <img
                  src={usecase.image}
                  alt={usecase.title}
                  className="absolute inset-0 w-full h-full object-cover opacity-60 transition-all duration-300 group-hover:opacity-0 pointer-events-none"
                />
                {/* Video: hidden by default, visible and plays on group-hover */}
                <video
                  ref={(el) => { usecaseVideoRefs.current[index] = el; }}
                  src={usecase.video}
                  muted
                  loop
                  playsInline
                  className="absolute inset-0 w-full h-full object-cover opacity-0 transition-opacity duration-300 group-hover:opacity-100 pointer-events-none"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-[#07080A] via-[#07080A]/50 to-transparent pointer-events-none" />
                <div className="absolute bottom-0 left-0 right-0 p-6 pointer-events-none">
                  <div className="w-10 h-10 rounded-lg bg-[#DFFF00]/20 flex items-center justify-center mb-3">
                    <usecase.icon size={20} className="text-[#DFFF00]" />
                  </div>
                  <h3 className="text-lg font-semibold">{usecase.title}</h3>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Latest Updates Section */}
      <section ref={newsRef} className="py-24 px-6 lg:px-8 border-y border-white/5">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-12">
            <div>
              <span className="label-mono mb-4 block">Latest Updates</span>
              <h2 className="text-3xl md:text-4xl font-semibold">News & Updates</h2>
            </div>
            <Link
              to="/blog"
              className="hidden md:flex items-center gap-2 text-[#A7B0B7] hover:text-[#DFFF00] transition-colors"
            >
              View all <ArrowRight size={18} />
            </Link>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {postsLoading ? (
              [...Array(3)].map((_, i) => (
                <div key={i} className="news-card card-vocence overflow-hidden animate-pulse">
                  <div className="h-48 bg-white/5" />
                  <div className="p-6 space-y-3">
                    <div className="h-4 bg-white/10 rounded w-1/3" />
                    <div className="h-5 bg-white/10 rounded w-full" />
                    <div className="h-4 bg-white/10 rounded w-full" />
                    <div className="h-4 bg-white/10 rounded w-2/3" />
                  </div>
                </div>
              ))
            ) : latestPosts.length === 0 ? (
              <p className="col-span-full text-center text-[#A7B0B7] py-8">No blog posts yet.</p>
            ) : (
              latestPosts.map((post) => (
                <Link
                  key={post.id}
                  to={`/blog/${post.id}`}
                  className="news-card card-vocence overflow-hidden group cursor-pointer block"
                >
                  <div className="h-48 overflow-hidden">
                    <img
                      src={blogImageUrl(post.image)}
                      alt={post.title}
                      className="w-full h-full object-cover group-hover:scale-110 group-hover:brightness-110 transition-all duration-500"
                    />
                  </div>
                  <div className="p-6">
                    <span className="inline-block px-3 py-1 rounded-full bg-white/5 text-xs font-mono text-[#A7B0B7] mb-3">
                      {post.category}
                    </span>
                    <h3 className="text-lg font-semibold mb-2 group-hover:text-[#DFFF00] transition-colors">
                      {post.title}
                    </h3>
                    <p className="text-sm text-[#A7B0B7] mb-4 line-clamp-2">
                      {post.excerpt}
                    </p>
                    <div className="flex items-center gap-2 text-xs text-[#666]">
                      <span>{post.date}</span>
                      <span>•</span>
                      <span>{post.read_time}</span>
                    </div>
                  </div>
                </Link>
              ))
            )}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-24 px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="mb-10 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
            <div className="max-w-xl">
              <span className="label-mono mb-4 block">Pricing</span>
              <h2 className="text-3xl md:text-4xl font-semibold text-white">Plans for prompt-controlled TTS</h2>
              <p className="mt-3 text-sm text-[#A7B0B7] md:text-base">
                We are currently supporting <span className="font-medium text-white">PromptTTS</span> only.
              </p>
            </div>
            <div className="flex flex-wrap items-center gap-3 sm:justify-end">
              <Link
                to="/docs/pricing"
                className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:border-white/25 hover:bg-white/10"
              >
                Pricing in Docs
                <ArrowRight size={16} />
              </Link>
              <Link
                to="/pricing"
                className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-[#DFFF00]/25 bg-[#DFFF00]/10 px-4 py-2.5 text-sm font-semibold text-[#F3FFD0] transition-colors hover:bg-[#DFFF00]/15"
              >
                Upgrade plan
                <ArrowRight size={16} />
              </Link>
            </div>
          </div>

          <PricingPlans compact forOverview />
        </div>
      </section>

      {/* Roadmap Section – horizontal timeline + one card at a time */}
      <section className="py-24 px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <span className="label-mono mb-4 block">Roadmap</span>
            <h2 className="text-3xl md:text-4xl font-semibold mb-4">Project Roadmap</h2>
            <p className="text-[#A7B0B7] max-w-2xl mx-auto">
              Our journey to build the Voice Intelligence Layer: from foundation to ecosystem expansion across PromptTTS, STT, STS, voice cloning, TTM, and voice agents.
            </p>
          </div>

          {/* Horizontal timeline: line with Q1 — Q2 — Q3 nodes */}
          <div className="flex items-center w-full mb-8">
            <div className="flex-1 h-0.5 bg-white/10 rounded-l" aria-hidden />
            {ROADMAP_QUARTERS.map((q, index) => (
              <span key={index} className="flex items-center shrink-0">
                <button
                  type="button"
                  onClick={() => setRoadmapActive(index)}
                  className={`flex flex-col items-center gap-2 transition-colors ${
                    roadmapActive === index ? 'opacity-100' : 'opacity-70 hover:opacity-100'
                  }`}
                >
                  <div
                    className={`w-10 h-10 rounded-full border-2 flex items-center justify-center transition-colors ${
                      roadmapActive === index
                        ? 'border-[#DFFF00] bg-[#DFFF00]'
                        : q.completed
                          ? 'border-[#DFFF00]/60 bg-[#DFFF00]/20'
                          : 'border-white/20 bg-white/5'
                    }`}
                  >
                    {q.completed ? <Check size={18} className={roadmapActive === index ? 'text-[#07080A]' : 'text-[#DFFF00]'} /> : <span className="text-xs font-medium text-[#A7B0B7]">{index + 1}</span>}
                  </div>
                  <span className={`text-sm font-medium whitespace-nowrap ${roadmapActive === index ? 'text-white' : 'text-[#A7B0B7]'}`}>
                    Q{index + 1}
                  </span>
                </button>
                {index < ROADMAP_QUARTERS.length - 1 && <div className="w-8 md:w-16 flex-shrink-0 h-0.5 bg-white/10" aria-hidden />}
              </span>
            ))}
            <div className="flex-1 h-0.5 bg-white/10 rounded-r" aria-hidden />
          </div>

          {/* Single card: only the active quarter's content */}
          <div className="rounded-2xl border border-white/10 bg-[#0a0a0a]/90 overflow-hidden">
            <div className="p-6 md:p-8">
              <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
                {ROADMAP_QUARTERS[roadmapActive].completed && <Check size={20} className="text-[#DFFF00]" />}
                {ROADMAP_QUARTERS[roadmapActive].phase}
              </h3>
              <ul className="text-[#A7B0B7] text-sm space-y-2 list-disc list-outside pl-6 leading-relaxed">
                {ROADMAP_QUARTERS[roadmapActive].items.map((bullet, i) => (
                  <li key={i}>{bullet}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-2 gap-6">
            {/* Studio CTA */}
            <div className="card-vocence p-8 md:p-12 relative overflow-hidden">
              <div className="relative z-10">
                <span className="label-mono mb-4 block">Try the Studio</span>
                <h3 className="text-2xl md:text-3xl font-semibold mb-4">
                  Generate Speech in Seconds
                </h3>
                <p className="text-[#A7B0B7] mb-6">
                  Generate speech, clone voices, and tune style prompts—in one interface.
                </p>
                <Link to="/studio/tts" className="btn-primary">
                  Launch Studio
                  <ArrowRight size={18} className="ml-2" />
                </Link>
              </div>
              <img
                src="/studio_ui.jpg"
                alt="Studio UI"
                className="absolute right-0 bottom-0 w-2/3 opacity-30 hover:opacity-40 hover:scale-105 transition-all duration-500"
              />
            </div>

            {/* Docs CTA */}
            <div className="card-vocence p-8 md:p-12 relative overflow-hidden">
              <div className="relative z-10">
                <span className="label-mono mb-4 block">Build with Vocence</span>
                <h3 className="text-2xl md:text-3xl font-semibold mb-4">
                  Developer Ready
                </h3>
                <p className="text-[#A7B0B7] mb-6">
                  REST API, Python SDK, and real-time WebSocket streams. Get started in
                  minutes.
                </p>
                <Link to="/docs" className="btn-primary">
                  Read Docs
                  <ArrowRight size={18} className="ml-2" />
                </Link>
              </div>
              <img
                src="/docs_code.jpg"
                alt="Code"
                className="absolute right-0 bottom-0 w-2/3 opacity-30 hover:opacity-40 hover:scale-105 transition-all duration-500"
              />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
