/**
 * Vocence Agent — shared types for the agents UI and API client.
 *
 * Voice is mandatory for every agent (Vocence is voice-first). Knowledge
 * agents respond to chat; Goal agents run autonomously toward a target.
 */

export type AgentType = 'knowledge' | 'goal';
export type AgentStatus = 'draft' | 'active' | 'paused' | 'archived';
export type AgentRunStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

export interface AgentConfig {
  /** Concise human-readable description of what the agent does. */
  purpose: string;
  /** System prompt — the LLM instruction block. Generated by AI, editable. */
  system_prompt: string;
  /** Free-form knowledge text injected into context. v1: text only. */
  knowledge: string;
  /** Voice preset name (Qwen3-TTS speaker). Required. */
  voice: string;
  /** Synthesis language. Default 'English'. */
  language: string;
  /** LLM model id (Chutes-served). */
  llm_model: string;
  /** Sampling temperature (0–2). */
  temperature: number;
  /** For Goal agents only — the user-stated goal. */
  goal?: string;
  /** For Goal agents — natural-language description of "done". */
  success_metric?: string;
  /** For Goal agents — hard cap on iterations. */
  max_iterations?: number;
}

export interface Agent {
  id: string;
  user_id: string;
  type: AgentType;
  status: AgentStatus;
  name: string;
  config: AgentConfig;
  created_at: string;
  updated_at: string;
  last_run_at?: string | null;
  run_count: number;
}

export interface AgentRunIteration {
  index: number;
  thought: string;       // LLM's plan/reasoning for this iteration
  output: string;        // produced content
  score: number;         // self-assessed score (0–1)
  rationale: string;     // why that score
  created_at: string;
}

export interface AgentRun {
  id: string;
  agent_id: string;
  status: AgentRunStatus;
  goal: string;
  success_metric: string;
  iterations: AgentRunIteration[];
  best_output?: string;
  best_score?: number;
  error?: string | null;
  started_at: string;
  finished_at?: string | null;
}

export interface AgentDraftRequest {
  /** User's natural-language description of the agent they want. */
  description: string;
  /** Optional: nudge toward a type. If omitted, the LLM picks. */
  type_hint?: AgentType;
  /** Existing draft to refine. If present, the LLM revises rather than starts over. */
  existing?: Partial<AgentConfig> & { name?: string; type?: AgentType };
}

export interface AgentDraftResponse {
  name: string;
  type: AgentType;
  config: AgentConfig;
  /** Short note from the architect explaining choices — shown in the chat. */
  note: string;
}

/** Starter templates rendered in the empty-state list. */
export interface AgentTemplate {
  id: string;
  name: string;
  type: AgentType;
  blurb: string;          // one-line for the card
  seed_prompt: string;    // prefilled in the builder when chosen
}

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'support-bot',
    name: 'Customer Support',
    type: 'knowledge',
    blurb: 'A friendly support voice agent that answers FAQs and triages issues.',
    seed_prompt:
      'A customer support voice agent for a SaaS product. Friendly, concise. Knows our pricing, common errors, and account questions. Escalates to a human when unsure.',
  },
  {
    id: 'study-coach',
    name: 'Study Coach',
    type: 'knowledge',
    blurb: 'Quizzes you on a topic, explains tricky bits, encourages progress.',
    seed_prompt:
      'A study coach voice agent. Asks me questions on a topic I provide, explains incorrect answers patiently, and tracks what I get right vs wrong in the conversation.',
  },
  {
    id: 'daily-summarizer',
    name: 'Daily Summarizer',
    type: 'goal',
    blurb: 'Iteratively drafts a punchy daily summary from notes you provide.',
    seed_prompt:
      'A goal agent that takes a brain dump of my day and produces a one-paragraph summary I would actually read tomorrow. Iterates until the summary is under 80 words and would make sense to someone who was not there.',
  },
  {
    id: 'cold-email',
    name: 'Cold-Email Refiner',
    type: 'goal',
    blurb: 'Iterates on a cold email until it sounds human, short, and clear.',
    seed_prompt:
      'A goal agent that refines a cold email I provide. Target: under 90 words, no buzzwords, a single clear ask, sounds like a human. Iterates and rates itself each round.',
  },
];

export const DEFAULT_AGENT_CONFIG: AgentConfig = {
  purpose: '',
  system_prompt: '',
  knowledge: '',
  // Default to a sample voice id from the gallery (see /src/data/sampleVoices.ts).
  // The voicechat backend resolves the id to either a Qwen3 speaker shortcut
  // (legacy) or a voice-cloned synthesis using the matching reference clip.
  voice: 'design-aria',
  language: 'English',
  llm_model: '',
  temperature: 0.6,
};
