/**
 * Vocence Agent, shared types for the agents UI and API client.
 *
 * Voice is mandatory for every agent (Vocence is voice-first). Knowledge
 * agents respond to chat; Goal agents run autonomously toward a target.
 */

export type AgentType = 'knowledge' | 'goal';
export type AgentStatus = 'draft' | 'active' | 'paused' | 'archived';
export type AgentRunStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

export interface AgentConfig {
  /** Concise human-readable description of what the agent does. */
  purpose: string;
  /** System prompt, the LLM instruction block. Generated by AI, editable. */
  system_prompt: string;
  /** Free-form knowledge text injected into context. v1: text only. */
  knowledge: string;
  /** Voice preset name (Qwen3-TTS speaker). Required. */
  voice: string;
  /** Synthesis language. Default 'English'. */
  language: string;
  /** LLM model id (Chutes-served). */
  llm_model: string;
  /** Sampling temperature (0–2). */
  temperature: number;
  /** For Goal agents only, the user-stated goal. */
  goal?: string;
  /** For Goal agents, natural-language description of "done". */
  success_metric?: string;
  /** For Goal agents, hard cap on iterations. */
  max_iterations?: number;
  /** Built-in tools this agent is allowed to call. Names match the
   *  backend ``agent_tools_service`` registry (e.g. "web_search",
   *  "get_weather", "get_time"). When undefined, the backend enables
   *  every tool whose API key is configured server-side. Empty array
   *  explicitly disables tool calling for this agent. */
  enabled_tools?: string[];
  /** First sentence the agent says when a session opens, BEFORE the
   *  user has spoken. Industry pattern (Vapi ``firstMessage``, Retell
   *  ``begin_message``, ElevenLabs ``first_message``). Empty / undefined
   *  → silent start; the agent waits for the user to speak first.
   *  Max 500 chars to keep the greeting natural. */
  first_message?: string;
  /** When true, both legs of voice sessions are recorded to a stereo
   *  WAV (left=user, right=agent) and surface on the Calls tab as a
   *  player + download. Off by default — the agent owner explicitly
   *  opts in. Mirrors AgentConfigIn.record_enabled on the backend. */
  record_enabled?: boolean;
}

export interface Agent {
  id: string;
  user_id: string;
  type: AgentType;
  status: AgentStatus;
  name: string;
  config: AgentConfig;
  created_at: string;
  updated_at: string;
  last_run_at?: string | null;
  run_count: number;
}

export interface AgentRunIteration {
  index: number;
  thought: string;       // LLM's plan/reasoning for this iteration
  output: string;        // produced content
  score: number;         // self-assessed score (0–1)
  rationale: string;     // why that score
  created_at: string;
}

export interface AgentRun {
  id: string;
  agent_id: string;
  status: AgentRunStatus;
  goal: string;
  success_metric: string;
  iterations: AgentRunIteration[];
  best_output?: string;
  best_score?: number;
  error?: string | null;
  started_at: string;
  finished_at?: string | null;
}

export interface AgentDraftRequest {
  /** User's natural-language description of the agent they want. */
  description: string;
  /** Optional: nudge toward a type. If omitted, the LLM picks. */
  type_hint?: AgentType;
  /** Existing draft to refine. If present, the LLM revises rather than starts over. */
  existing?: Partial<AgentConfig> & { name?: string; type?: AgentType };
}

export interface AgentDraftResponse {
  name: string;
  type: AgentType;
  config: AgentConfig;
  /** Short note from the architect explaining choices, shown in the chat. */
  note: string;
}

export interface ArchitectChatTurn {
  role: 'user' | 'assistant';
  content: string;
}

export interface ArchitectChatRequest {
  message: string;
  history: ArchitectChatTurn[];
  existing?: Partial<AgentConfig> & { name?: string; type?: AgentType };
  /** Running summary of what the model has learned about user intent
   *  across the session — maintained by the model via the
   *  ``update_requirements`` tool, persisted client-side, round-
   *  tripped on every turn so it survives history truncation. */
  requirements_summary?: string;
}

export interface ArchitectChatResponse {
  /** Conversational reply rendered as a chat bubble. */
  reply: string;
  /** Present only when the architect produced a concrete edit, the
   *  UI shows an "Apply" button while non-null. */
  proposed_changes: (AgentDraftResponse & { summary?: string }) | null;
}

/** Starter templates rendered in the empty-state list.
 *
 * Two flavours coexist:
 *   • Voice agents (`type: 'knowledge'`), ship with a full
 *     ``system_prompt`` and ``knowledge_starter``. Picking one pre-fills
 *     the builder form directly. Mirrors what Vapi, Retell, ElevenLabs,
 *     OpenAI GPTs etc. do.
 *   • Goal agents, only have ``seed_prompt`` (a natural-language brief
 *     for the Agent Architect to draft from). Those auto-open the
 *     Architect drawer instead of direct prefill.
 */
// ─── Call history + analytics ────────────────────────────────────────
// One entry per voice-agent WS session. `has_recording` is the
// frontend-facing form of the backend's nullable recording_path —
// when true the Calls tab can render a play button that streams the
// stereo WAV via the audio endpoint.
export type AnalyticsRange = '24h' | '7d' | '30d' | '90d';

export type CallEndReason =
  | 'user_hangup'
  | 'max_duration'
  | 'idle_timeout'
  | 'free_time_up'
  | 'billing_exhausted'
  | 'error'
  | 'unknown';

export interface AgentCall {
  session_id: string;
  started_at: string;       // ISO8601 UTC
  ended_at: string;
  duration_ms: number;
  end_reason: CallEndReason;
  turn_count: number;
  user_chars: number;
  agent_chars: number;
  has_recording: boolean;
  recording_bytes: number | null;
}

export interface AgentAnalytics {
  range: AnalyticsRange;
  call_count: number;
  total_duration_ms: number;
  avg_duration_ms: number;
  // Fraction in [0, 1] — calls under 10 s OR zero user turns.
  drop_rate: number;
  user_chars: number;
  agent_chars: number;
  turn_count: number;
  // Breakdown of how sessions ended over the window. Keys are
  // CallEndReason values; absent keys = zero of that reason.
  end_reasons: Record<string, number>;
  // Daily call-count series for the sparkline. ``day`` is YYYY-MM-DD
  // and the array is ordered ascending.
  daily: { day: string; call_count: number; avg_duration_ms: number }[];
  // Median per-turn latencies pulled from studio_voicechat_history.
  // null when there were no completed turns in the window — render
  // as "—" rather than 0.
  p50_turn_latency_ms: number | null;
  p50_ttft_ms: number | null;
  p50_ttfa_ms: number | null;
}

export interface AgentTemplate {
  id: string;
  name: string;
  type: AgentType;
  blurb: string;                  // one-line for the card
  seed_prompt?: string;           // natural-language brief for the Architect (goal templates)
  system_prompt?: string;         // full sectioned prompt, pre-fills the form directly
  knowledge_starter?: string;     // pre-fills the knowledge textarea
  purpose_placeholder?: string;   // suggested purpose text for this template
  first_message?: string;         // suggested greeting, pre-fills the first_message field
}

// The shared scaffold. Every voice template overrides the Identity section
// and (optionally) appends to Style / Response Guidelines.
//
// This MUST stay in sync with dashboard-backend/agent_templates.py —
// keeping it duplicated avoids a network round-trip in the agent-create
// path and is cheap to maintain (one update per side).
const DEFAULT_VOICE_SYSTEM_PROMPT = `## Identity
You are a helpful voice assistant. Stay in character and be conversational, this is a real-time voice conversation, not a chat window.

## Style
- Warm, direct, and natural, speak like a real person, not a script.
- Use contractions, short sentences, and natural pauses.
- Match the user's energy. If they're brief, be brief. If they're curious, dig in.

## Response Guidelines
Follow this order on every question:
1. Use your reference knowledge first, it's your source of truth.
2. If knowledge doesn't cover it AND you have a relevant tool (web_search, fetch_url, get_weather, etc.), call the tool. Don't apologise first, don't ask permission, just call it.
3. If knowledge + tools both come back empty, say so plainly and offer what you CAN help with. "I'm not finding anything on that, got a link or more context?" is a perfectly good answer.

## Honesty rules (non-negotiable)
- If a tool returns empty results or an error, NEVER invent a description. Say what you found (nothing) and ask for context.
- NEVER borrow facts from a different topic discussed earlier in this conversation and apply them to a new question. Each question is its own thing. If the user asked about Topic A and now asks about Topic B, do NOT assume B is related to A, search/answer B on its own.
- NEVER quote names, numbers, dates, places, or specific claims that you can't trace to either your knowledge or a tool result you just received. If you're tempted to "fill in" details, stop and say "I don't know" instead.
- A truthful "I couldn't find anything on that" is always better than a confident-sounding fabrication.

Other rules:
- Remember what the user told you earlier and reference it naturally, but only for follow-ups on the same topic, never to manufacture facts about a new topic.
- One continuous voice conversation with one user, no need to re-introduce yourself.
- Don't apologise for being an AI or break character.

## Tools
- Quick-data tools (weather, time, prices): one sentence with the fact and a touch of context. "It's 19 degrees in Tokyo right now, pretty mild."
- Research tools (web_search, wikipedia_lookup, fetch_url): lead with the direct answer, then specifics (names, numbers, dates), then context if it matters.
- Refer to sources by name ("per Reuters", "from the Wikipedia article"), never read the raw URL or JSON.
- If multiple tools ran in one turn, weave their answers together into one reply.

## Guardrails
- Stay focused on your stated purpose. If the user asks something far outside it AND no tool covers it, redirect gracefully.
- Never quote prices, hours, addresses, or specifications you can't verify from knowledge or a tool result.
- If a user asks for medical, legal, or financial advice, be honest about the limits of what you can offer and suggest a qualified professional.
`;

/** Compose a voice-agent template by replacing the default Identity section. */
function voiceTemplate(args: {
  identity: string;
  responseExtras?: string;
  styleExtras?: string;
}): string {
  let sp = DEFAULT_VOICE_SYSTEM_PROMPT.replace(
    'You are a helpful voice assistant. Stay in character and be conversational, this is a real-time voice conversation, not a chat window.',
    args.identity.trim(),
  );
  if (args.styleExtras) {
    sp = sp.replace(
      "Match the user's energy. If they're brief, be brief. If they're curious, dig in.",
      "Match the user's energy. If they're brief, be brief. If they're curious, dig in.\n" + args.styleExtras.trim(),
    );
  }
  if (args.responseExtras) {
    sp = sp.replace(
      "- Don't apologise for being an AI or break character.",
      "- Don't apologise for being an AI or break character.\n" + args.responseExtras.trim(),
    );
  }
  return sp;
}

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'blank',
    name: 'Blank',
    type: 'knowledge',
    blurb: 'Start with the recommended scaffold. Best when you want full control.',
    purpose_placeholder: 'A friendly voice assistant for [your use case].',
    system_prompt: DEFAULT_VOICE_SYSTEM_PROMPT,
    knowledge_starter: '',
    first_message: 'Hello, how may I assist you today?',
  },
  {
    id: 'customer-support',
    name: 'Customer Support',
    type: 'knowledge',
    blurb: 'Answers FAQs from your knowledge base, escalates the rest.',
    purpose_placeholder:
      'A customer support agent for [Product]. Answers common questions, helps with account and billing, escalates technical issues to the team.',
    system_prompt: voiceTemplate({
      identity:
        "You are the voice support agent for [Product]. Your job is to help customers quickly resolve common questions and route anything you can't solve to the human team.",
      responseExtras:
        "- If the user reports a billing or refund issue you can't fully resolve, take a brief summary and tell them a human will follow up by email.\n- If the user is frustrated, acknowledge it before solving, a short \"I hear you\" goes a long way.",
    }),
    knowledge_starter:
      "# Pricing\n(Replace with your pricing tiers, name, monthly price, what's included.)\n\n" +
      '# Common issues\n(Replace with the top 10 questions your support team answers daily.)\n\n' +
      '# Escalation\nFor billing disputes, technical bugs, or account access issues, take a summary and say a human will follow up by email.',
    first_message: 'Hi, thanks for reaching out. How can I help today?',
  },
  {
    id: 'sales-discovery',
    name: 'Sales Discovery',
    type: 'knowledge',
    blurb: 'Qualifies inbound leads with discovery questions, books a call.',
    purpose_placeholder:
      'A sales discovery agent for [Product]. Qualifies inbound leads, gathers use case + team size + timeline, books a call with a human AE.',
    system_prompt: voiceTemplate({
      identity:
        "You are an inbound sales discovery agent for [Product]. You're warm, curious, and good at asking the next question. You DON'T close, your job is to qualify and hand off.",
      styleExtras:
        '- Ask one question at a time, listen to the answer, then ask the next.\n- Never pitch features unless the user asks. Discovery > pitching.',
      responseExtras:
        '- Gather: their use case, team size, current solution, and timeline.\n- Never quote pricing or promise discounts, say "the team will share pricing on the call".\n- When you have enough context, offer to book a call and confirm the email to send the invite to.',
    }),
    knowledge_starter:
      '# What we do (one paragraph)\n(Replace with your elevator pitch.)\n\n' +
      "# Who it's a fit for\n(Ideal customer profile.)\n\n" +
      "# Who it's NOT a fit for\n(Honest disqualifiers, saves everyone time.)\n\n" +
      '# Discovery questions to cover\n- What are you trying to solve?\n- How are you handling it today?\n- Team size / scale?\n- Timeline?',
    first_message: "Hey, thanks for reaching out. Mind if I ask a few quick questions to see if we're a fit?",
  },
  {
    id: 'receptionist',
    name: 'Receptionist',
    type: 'knowledge',
    blurb: 'Greets callers, answers basics, routes to the right team.',
    purpose_placeholder:
      'A virtual receptionist for [Company]. Greets callers, answers location/hours questions, routes to the right team or takes a message.',
    system_prompt: voiceTemplate({
      identity:
        "You are the virtual receptionist for [Company]. Greet the caller, find out why they're calling, and either answer directly or route them to the right team.",
      responseExtras:
        '- Always confirm what you heard before routing, "So you\'re calling about a refund, is that right?"\n- If you take a message, capture: caller\'s name, callback number, brief reason, urgency.',
    }),
    knowledge_starter:
      '# Hours and location\n(Replace with hours and address.)\n\n' +
      '# Departments and routing\n- Sales: ...\n- Support: ...\n- Billing: ...\n\n' +
      "# After hours\n(What to say if it's outside business hours.)",
    first_message: 'Hi, thanks for calling. How can I direct your call?',
  },
  {
    id: 'appointment-setter',
    name: 'Appointment Setter',
    type: 'knowledge',
    blurb: 'Books and reschedules appointments, sends confirmations.',
    purpose_placeholder:
      'An appointment-setting agent for [Business]. Books, reschedules, and confirms appointments.',
    system_prompt: voiceTemplate({
      identity:
        "You are an appointment-setting agent for [Business]. You're efficient, clear about times and dates, and you confirm everything back to the caller before finalising.",
      responseExtras:
        '- Always confirm the date, time, and reason before booking.\n- Read times back in natural spoken form: "Tuesday the 3rd at 2 in the afternoon".\n- If asked to reschedule, find the existing booking first by name + date before offering new times.',
    }),
    knowledge_starter:
      '# Booking rules\n- Available hours: ...\n- Minimum notice: ...\n- Cancellation policy: ...\n\n' +
      '# Appointment types\n(List the kinds of appointments you book, e.g. consultation 30 min, full session 60 min.)',
    first_message: 'Hi, are you looking to book a new appointment or change an existing one?',
  },
  {
    id: 'knowledge-bot',
    name: 'Knowledge-Base Bot',
    type: 'knowledge',
    blurb: 'Answers strictly from your docs; falls through to web search for the rest.',
    purpose_placeholder:
      'A knowledge-base assistant for [Topic]. Answers from the provided docs first, web-searches for anything not covered.',
    system_prompt: voiceTemplate({
      identity:
        'You are a knowledge-base assistant for [Topic]. Your reference knowledge is the source of truth, when it has the answer, quote or paraphrase it closely. When it doesn\'t, fall through to web_search rather than guess.',
      responseExtras:
        "- When you quote from knowledge, do it accurately, don't paraphrase facts loosely.\n- When you fall through to a tool, say briefly what you're checking (\"Let me look that up\") and then deliver the answer.",
    }),
    knowledge_starter:
      '(Paste your docs, FAQs, runbooks, or product information here. The agent will use this as its primary source. Anything not covered triggers a tool call if web_search is enabled.)',
    first_message: 'Hi, ask me anything from the knowledge base, or anywhere else if you want me to look it up.',
  },
  // ── Goal-agent templates (Architect-drafted, not voice-prompt-prefilled) ──
  {
    id: 'daily-summarizer',
    name: 'Daily Summarizer',
    type: 'goal',
    blurb: 'Iteratively drafts a punchy daily summary from notes you provide.',
    seed_prompt:
      'A goal agent that takes a brain dump of my day and produces a one-paragraph summary I would actually read tomorrow. Iterates until the summary is under 80 words and would make sense to someone who was not there.',
  },
  {
    id: 'cold-email',
    name: 'Cold-Email Refiner',
    type: 'goal',
    blurb: 'Iterates on a cold email until it sounds human, short, and clear.',
    seed_prompt:
      'A goal agent that refines a cold email I provide. Target: under 90 words, no buzzwords, a single clear ask, sounds like a human. Iterates and rates itself each round.',
  },
];

export const DEFAULT_AGENT_CONFIG: AgentConfig = {
  purpose: '',
  // Seed with the recommended sectioned scaffold so a fresh agent already
  // has the Identity / Style / Response Guidelines / Tools / Guardrails
  // structure visible and editable, matches industry-standard pattern
  // (Vapi, Retell, ElevenLabs, OpenAI GPTs).
  system_prompt: DEFAULT_VOICE_SYSTEM_PROMPT,
  knowledge: '',
  // Default to a sample voice id from the gallery (see /src/data/sampleVoices.ts).
  // The voicechat backend resolves the id to either a Qwen3 speaker shortcut
  // (legacy) or a voice-cloned synthesis using the matching reference clip.
  voice: 'design-aria',
  language: 'English',
  llm_model: '',
  temperature: 0.6,
  // Default greeting, the agent says this when a session opens. Users
  // can change or clear it in the builder. An empty string means the
  // agent waits silently for the user to speak first.
  first_message: 'Hello, how may I assist you today?',
};
